apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/modelServingSupport: '["single"]'
  labels:
    opendatahub.io/dashboard: "true"
  name: cpuvllm-serving-runtime
  namespace: redhat-ods-applications
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  metadata:
    annotations:
      opendatahub.io/apiProtocol: REST
      openshift.io/display-name: customCPUvLLM
    name: customcpuvllm
  spec:
    builtInAdapter:
      modelLoadingTimeoutMillis: 90000
    containers:
    - args:
      - --model
      - /mnt/models/
      - --download-dir
      - /models-cache
      - --port
      - "8080"
      - --max-model-len
      - "2048"
      image: quay.io/rh-aiservices-bu/vllm-cpu-openai-ubi9:0.3
      name: kserve-container
      ports:
      - containerPort: 8080
        name: http1
        protocol: TCP
    multiModel: false
    supportedModelFormats:
    - autoSelect: true
      name: pytorch
