apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-oauth: "true"
    opendatahub.io/image-display-name: Standard Data Science
    notebooks.opendatahub.io/oauth-logout-url: ""
    opendatahub.io/accelerator-name: ""
    openshift.io/description: ""
    openshift.io/display-name: elyra-docling-workbench
    notebooks.opendatahub.io/last-image-selection: "s2i-generic-data-science-notebook:2024.2"
  name: elyra-docling-workbench
  namespace: summit-project
spec:
  template:
    spec:
      affinity: {}
      containers:
        - name: elyra-docling-workbench
          image: "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2"
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 8Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/ai-example-training/elyra-docling-workbench/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/ai-example-training/elyra-docling-workbench/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
		    - '--provider=openshift'
		    - '--https-address=:8443'
		    - '--http-address='
		    - '--openshift-service-account=elyra-docling-workbench'
		    - '--cookie-secret-file=/etc/oauth/config/cookie_secret'
		    - '--cookie-expire=24h0m0s'
		    - '--tls-cert=/etc/tls/private/tls.crt'
		    - '--tls-key=/etc/tls/private/tls.key'
		    - '--upstream=http://localhost:8888'
		    - '--upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
		    - '--email-domain=*'
		    - '--skip-provider-button'
		    - '--openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"elyra-docling-workbench","namespace":"$(NAMESPACE)"}'
		    - '--logout-url=https://rhods-dashboard-redhat-ods-applications.apps.my-cluster.com/projects/summit-project?notebookLogout=elyra-docling-workbench'
		    - name: JUPYTER_IMAGE
		      value: "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-generic-data-science-notebook:2024.2"
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src
              name: elyra-docling-workbench
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/oauth/config
              name: oauth-config
            - mountPath: /etc/tls/private
              name: tls-certificates
          workingDir: /opt/app-root/src
      enableServiceLinks: false
      serviceAccountName: elyra-docling-workbench
      volumes:
        - name: elyra-docling-workbench
          persistentVolumeClaim:
            claimName: elyra-docling-workbench
        - emptyDir:
            medium: Memory
          name: shm
        - name: oauth-config
          secret:
            defaultMode: 420
            secretName: test-ssl-oauth-config
        - name: tls-certificates
          secret:
            defaultMode: 420
            secretName: elyra-docling-workbench-tls
