apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: simple-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: start-dsp-pipeline-run-
      spec:
        pipelineRef:
          name: start-dsp-pipeline
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
